In [1]:
import  numpy as np

Uniform and Normal Distribution

In [ ]:
d1=np.random.rand(4)
print(d1)

[0.85102217 0.14431423 0.76513668 0.44042169]


In [ ]:
d2=np.random.rand(4,3)
print(d2)

[[0.29568379 0.95178816 0.79929786]
 [0.83139102 0.53124953 0.36407219]
 [0.68518184 0.00606947 0.80079483]
 [0.77278205 0.4663571  0.60837053]]


In [ ]:
d3=np.random.randint(1,100,3)
print(d3)

[23 25 91]


In [ ]:
print(d2.max())
print(d2.min())


0.9517881622161882
0.006069473106710799
